import json
import os

def create_notebook():
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# 🧠 Computational Neurodynamics & ODE Jupyter Companion\n",
                    "### Target Audience: Physicians & Computational Neuroscience Researchers\n",
                    "### Focus: From LIF Electrophysiology to David Sussillo's RNN Population Dynamics & FORCE Algorithm\n",
                    "\n",
                    "This Jupyter Notebook is a companion to your Neurodynamics Learning App. It allows you to simulate, analyze, and visualize neural dynamics using Python, NumPy, and Matplotlib. We will progress through three core computational milestones:\n",
                    "1. **Single-Neuron Electrophysiology**: The Leaky Integrate-and-Fire (LIF) Model.\n",
                    "2. **Coupled Network Oscillations**: The Basal Ganglia STN-GPe Loop in Parkinson's Disease & DBS Forcing.\n",
                    "3. **Recurrent Neural Networks (RNNs) as Continuous Dynamical Systems**: David Sussillo's population dynamics, attractor state-space, phase plane vector fields, and the **FORCE Algorithm** (Sussillo & Abbott, 2009).\n",
                    "\n",
                    "---"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 1. Single-Neuron Electrophysiology: The LIF Model\n",
                    "The membrane potential $V(t)$ of a Leaky Integrate-and-Fire neuron is described by the linear first-order ordinary differential equation (ODE):\n",
                    "\n",
                    "$$\\tau_m \\frac{dV}{dt} = -(V - V_{rest}) + R_m I_{ext}(t)$$\n",
                    "\n",
                    "with a threshold condition: if $V(t) \\ge V_{th}$, the neuron spikes ($V(t) \\leftarrow V_{spike}$), and is immediately reset to a lower potential ($V(t) \\leftarrow V_{reset}$) and enters a refractory period.\n",
                    "\n",
                    "Let's write a numerical solver using **Euler's method** to integrate this ODE."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import numpy as np\n",
                    "import matplotlib.pyplot as plt\n",
                    "\n",
                    "# Define standard electrophysiological parameters\n",
                    "tau_m = 10.0      # Membrane time constant (ms)\n",
                    "V_rest = -70.0    # Resting potential (mV)\n",
                    "V_th = -55.0      # Action potential threshold (mV)\n",
                    "V_reset = -75.0   # Reset potential after spike (mV)\n",
                    "V_spike = 20.0    # Peak voltage during action potential (mV)\n",
                    "R_m = 1.0         # Membrane resistance (Gigaohms)\n",
                    "\n",
                    "# Time settings\n",
                    "dt = 0.1          # Integration time-step (ms)\n",
                    "T = 100.0         # Total simulation time (ms)\n",
                    "t = np.arange(0, T, dt)\n",
                    "\n",
                    "# Input current (constant stimulus)\n",
                    "I_ext = np.ones(len(t)) * 16.0  # 16 nA input current\n",
                    "\n",
                    "# Arrays to store results\n",
                    "V = np.zeros(len(t))\n",
                    "V[0] = V_rest\n",
                    "spikes = []\n",
                    "\n",
                    "# Euler Method Integration\n",
                    "for i in range(1, len(t)):\n",
                    "    # If the neuron spiked in the previous step, reset it\n",
                    "    if V[i-1] == V_spike:\n",
                    "        V[i] = V_reset\n",
                    "    else:\n",
                    "        # Calculate membrane rate of change (dV/dt)\n",
                    "        dVdt = (-(V[i-1] - V_rest) + R_m * I_ext[i-1]) / tau_m\n",
                    "        # Update voltage\n",
                    "        V[i] = V[i-1] + dVdt * dt\n",
                    "        \n",
                    "        # Check if threshold is crossed\n",
                    "        if V[i] >= V_th:\n",
                    "            V[i] = V_spike  # Action potential peak\n",
                    "            spikes.append(t[i])\n",
                    "\n",
                    "# Plotting\n",
                    "plt.figure(figsize=(12, 4), dpi=100)\n",
                    "plt.plot(t, V, label='Membrane Voltage $V(t)$', color='#2563eb', lw=2)\n",
                    "plt.axhline(V_th, color='#ef4444', linestyle='--', label='Threshold ($V_{th} = -55$ mV)', alpha=0.8)\n",
                    "plt.axhline(V_rest, color='#64748b', linestyle=':', label='Resting ($V_{rest} = -70$ mV)')\n",
                    "plt.title('Leaky Integrate-and-Fire (LIF) Neuron Dynamics (Constant Input)', fontsize=13)\n",
                    "plt.xlabel('Time (ms)', fontsize=11)\n",
                    "plt.ylabel('Membrane Potential (mV)', fontsize=11)\n",
                    "plt.legend(loc='upper right')\n",
                    "plt.grid(True, alpha=0.2)\n",
                    "plt.show()"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### 1.1 Sinusoidal/Oscillatory Input & Subthreshold Resonance\n",
                    "Real neural inputs are highly oscillatory. Let's see how our LIF model behaves when stimulated with a sinusoidal input current. We will study how the frequency of the input waves shapes the spiking pattern."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Simulation parameters\n",
                    "T_osc = 200.0\n",
                    "t_osc = np.arange(0, T_osc, dt)\n",
                    "\n",
                    "# Oscillation frequency (Hz = 1/s; so cycles per ms = frequency / 1000)\n",
                    "freq_hz = 15.0  # 15 Hz oscillations\n",
                    "freq_ms = freq_hz / 1000.0\n",
                    "\n",
                    "# Current oscillates: I(t) = Baseline + Amplitude * sin(2 * pi * f * t)\n",
                    "I_baseline = 14.0\n",
                    "I_amplitude = 8.0\n",
                    "I_ext_osc = I_baseline + I_amplitude * np.sin(2 * np.pi * freq_ms * t_osc)\n",
                    "\n",
                    "# Arrays to store results\n",
                    "V_osc = np.zeros(len(t_osc))\n",
                    "V_osc[0] = V_rest\n",
                    "\n",
                    "# Euler Method Integration\n",
                    "for i in range(1, len(t_osc)):\n",
                    "    if V_osc[i-1] == V_spike:\n",
                    "        V_osc[i] = V_reset\n",
                    "    else:\n",
                    "        dVdt = (-(V_osc[i-1] - V_rest) + R_m * I_ext_osc[i-1]) / tau_m\n",
                    "        V_osc[i] = V_osc[i-1] + dVdt * dt\n",
                    "        if V_osc[i] >= V_th:\n",
                    "            V_osc[i] = V_spike\n",
                    "\n",
                    "# Plotting\n",
                    "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 6), sharex=True, dpi=100)\n",
                    "ax1.plot(t_osc, V_osc, color='#0d9488', lw=2, label='Membrane Voltage $V(t)$')\n",
                    "ax1.axhline(V_th, color='#ef4444', linestyle='--', label='Threshold')\n",
                    "ax1.set_ylabel('Voltage (mV)', fontsize=11)\n",
                    "ax1.legend(loc='upper right')\n",
                    "ax1.grid(True, alpha=0.2)\n",
                    "ax1.set_title('LIF Response to Oscillatory Input Current', fontsize=13)\n",
                    "\n",
                    "ax2.plot(t_osc, I_ext_osc, color='#d97706', lw=1.5, label='Input Current $I(t)$')\n",
                    "ax2.set_xlabel('Time (ms)', fontsize=11)\n",
                    "ax2.set_ylabel('Current (nA)', fontsize=11)\n",
                    "ax2.legend(loc='upper right')\n",
                    "ax2.grid(True, alpha=0.2)\n",
                    "\n",
                    "plt.tight_layout()\n",
                    "plt.show()"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "---\n",
                    "## 2. Coupled Network Oscillations: The STN-GPe Loop in Parkinson's Disease\n",
                    "In the basal ganglia, the excitatory Subthalamic Nucleus (STN) and inhibitory Globus Pallidus externa (GPe) form a **coupled negative feedback loop**. In Parkinson's disease (dopamine depletion), this loop slips into pathological synchronous oscillations. Deep Brain Stimulation (DBS) injects high-frequency currents to disrupt these oscillations.\n",
                    "\n",
                    "Let's model the STN and GPe as two coupled differential equations describing their population activity levels ($V_S$ and $V_G$):\n",
                    "\n",
                    "$$\\tau_S \\frac{dV_S}{dt} = -(V_S - V_{S,rest}) - W_{GS} f(V_G) + I_{DBS}(t)$$\n",
                    "$$\\tau_G \\frac{dV_G}{dt} = -(V_G - V_{G,rest}) + W_{SG} f(V_S)$$\n",
                    "\n",
                    "where $f(V) = \\frac{1}{1 + e^{-k(V - V_{mid})}}$ is the non-linear sigmoid activation function."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# STN-GPe parameters\n",
                    "tau_S = 20.0       # STN time constant (ms)\n",
                    "tau_G = 20.0       # GPe time constant (ms)\n",
                    "V_S_rest = -60.0   # STN resting potential (mV)\n",
                    "V_G_rest = -60.0   # GPe resting potential (mV)\n",
                    "\n",
                    "# Coupling strengths\n",
                    "W_SG = 15.0        # Excitatory STN -> GPe connection\n",
                    "W_GS = 18.0        # Inhibitory GPe -> STN connection\n",
                    "\n",
                    "# Sigmoid activation parameters\n",
                    "V_mid = -50.0      # Midpoint activation (mV)\n",
                    "k = 0.2            # Slope parameter\n",
                    "\n",
                    "def f(V):\n",
                    "    return 1.0 / (1.0 + np.exp(-k * (V - V_mid)))\n",
                    "\n",
                    "# Simulation settings\n",
                    "dt_net = 0.2\n",
                    "T_net = 300.0\n",
                    "t_net = np.arange(0, T_net, dt_net)\n",
                    "\n",
                    "# DBS stimulation settings (High frequency forcing: 130 Hz)\n",
                    "dbs_freq_hz = 130.0\n",
                    "dbs_freq_ms = dbs_freq_hz / 1000.0\n",
                    "dbs_amplitude = 25.0\n",
                    "\n",
                    "# We simulate two conditions: Parkinsonian (pathological oscillation) vs. DBS Active\n",
                    "def simulate_network(with_dbs=False):\n",
                    "    V_S = np.zeros(len(t_net))\n",
                    "    V_G = np.zeros(len(t_net))\n",
                    "    V_S[0] = -55.0  # Slightly perturbed starting condition\n",
                    "    V_G[0] = -55.0\n",
                    "    \n",
                    "    for i in range(1, len(t_net)):\n",
                    "        # DBS forcing function\n",
                    "        I_dbs = dbs_amplitude * (np.sin(2 * np.pi * dbs_freq_ms * t_net[i-1]) > 0.0) if with_dbs else 0.0\n",
                    "        \n",
                    "        # STN derivative\n",
                    "        dVS_dt = (-(V_S[i-1] - V_S_rest) - W_GS * f(V_G[i-1]) + I_dbs) / tau_S\n",
                    "        # GPe derivative\n",
                    "        dVG_dt = (-(V_G[i-1] - V_G_rest) + W_SG * f(V_S[i-1])) / tau_G\n",
                    "        \n",
                    "        # Euler step\n",
                    "        V_S[i] = V_S[i-1] + dVS_dt * dt_net\n",
                    "        V_G[i] = V_G[i-1] + dVG_dt * dt_net\n",
                    "        \n",
                    "    return V_S, V_G\n",
                    "\n",
                    "# Run simulations\n",
                    "VS_parkinson, VG_parkinson = simulate_network(with_dbs=False)\n",
                    "VS_dbs, VG_dbs = simulate_network(with_dbs=True)\n",
                    "\n",
                    "# Plotting comparisons\n",
                    "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 6), sharex=True, dpi=100)\n",
                    "\n",
                    "ax1.plot(t_net, VS_parkinson, color='#ef4444', lw=2, label='STN (Parkinsonian Oscillation)')\n",
                    "ax1.plot(t_net, VG_parkinson, color='#f59e0b', lw=1.5, label='GPe', alpha=0.7)\n",
                    "ax1.set_ylabel('Voltage (mV)', fontsize=11)\n",
                    "ax1.set_title('Pathological Synchronization in Parkinsonian STN-GPe Loop', fontsize=13)\n",
                    "ax1.legend()\n",
                    "ax1.grid(True, alpha=0.2)\n",
                    "\n",
                    "ax2.plot(t_net, VS_dbs, color='#2563eb', lw=2, label='STN with High-Frequency DBS')\n",
                    "ax2.plot(t_net, VG_dbs, color='#06b6d4', lw=1.5, label='GPe', alpha=0.7)\n",
                    "ax2.set_xlabel('Time (ms)', fontsize=11)\n",
                    "ax2.set_ylabel('Voltage (mV)', fontsize=11)\n",
                    "ax2.set_title('DBS Forcing Disrupts Synchronization (Desynchronization effect)', fontsize=13)\n",
                    "ax2.legend()\n",
                    "ax2.grid(True, alpha=0.2)\n",
                    "\n",
                    "plt.tight_layout()\n",
                    "plt.show()"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "---\n",
                    "## 3. Recurrent Neural Networks (RNNs) as Continuous Dynamical Systems\n",
                    "Modern computational neuroscience shifts focus from single neurons to **population-level dynamics**. Following David Sussillo's pioneering work (*Computation through Neural Population Dynamics*, Nature Neuroscience 2013), a recurrent neural network with $N$ units can be modeled as a continuous-time dynamical system governed by a system of coupled first-order ODEs:\n",
                    "\n",
                    "$$\\tau \\frac{dx_i}{dt} = -x_i + \\sum_{j=1}^{N} W_{ij} \\tanh(x_j) + I_i(t)$$\n",
                    "\n",
                    "where:\n",
                    "- $x_i(t)$ is the activation state (e.g., membrane current) of unit $i$.\n",
                    "- $h_i(t) = \\tanh(x_i(t))$ is the firing rate of unit $i$ (bounded between -1 and 1).\n",
                    "- $W$ is the connectivity weight matrix ($N \\times N$).\n",
                    "- $\\tau$ is the time constant.\n",
                    "- $I_i(t)$ is the external input.\n",
                    "\n",
                    "To understand how this network performs computations, we analyze its **state space topology**, find **fixed points** (where $dx/dt = 0$), and visualize the **attractor landscape**."
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### 3.1 Phase Portrait and Vector Field of a 2-Unit RNN\n",
                    "Let's write a Python script to visualize the vector field, nullclines, and fixed points of a 2-unit recurrent network. The system is:\n",
                    "\n",
                    "$$\\tau \\frac{dx_1}{dt} = -x_1 + W_{11} \\tanh(x_1) + W_{21} \\tanh(x_2)$$\n",
                    "$$\\tau \\frac{dx_2}{dt} = -x_2 + W_{12} \\tanh(x_1) + W_{22} \\tanh(x_2)$$"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Connectivity weights for our 2-unit network\n",
                    "# We configure it to have two stable fixed points (bistable system, functioning as a 1-bit memory)\n",
                    "W_rnn = np.array([\n",
                    "    [1.5, -0.4],\n",
                    "    [-0.4, 1.5]\n",
                    "])\n",
                    "tau_rnn = 10.0\n",
                    "\n",
                    "def rnn_deriv(x, t=0):\n",
                    "    # x is a vector of shape (2,)\n",
                    "    rates = np.tanh(x)\n",
                    "    dxdt = (-x + np.dot(W_rnn, rates)) / tau_rnn\n",
                    "    return dxdt\n",
                    "\n",
                    "# Create grid in state space\n",
                    "x1_range = np.linspace(-3, 3, 30)\n",
                    "x2_range = np.linspace(-3, 3, 30)\n",
                    "X1, X2 = np.meshgrid(x1_range, x2_range)\n",
                    "\n",
                    "# Calculate vector field\n",
                    "U = np.zeros(X1.shape)\n",
                    "V_dir = np.zeros(X2.shape)\n",
                    "for idx in range(X1.shape[0]):\n",
                    "    for jdx in range(X1.shape[1]):\n",
                    "        x_vec = np.array([X1[idx, jdx], X2[idx, jdx]])\n",
                    "        dxdt = rnn_deriv(x_vec)\n",
                    "        U[idx, jdx] = dxdt[0]\n",
                    "        V_dir[idx, jdx] = dxdt[1]\n",
                    "\n",
                    "# Plot Phase Portrait\n",
                    "plt.figure(figsize=(8, 8), dpi=100)\n",
                    "plt.streamplot(X1, X2, U, V_dir, color=np.sqrt(U**2 + V_dir**2), cmap='viridis', density=1.2, arrowsize=1.2)\n",
                    "\n",
                    "# Plot Nullclines (where dx1/dt = 0 and dx2/dt = 0)\n",
                    "# dx1/dt = 0 => x1 = W_11 tanh(x1) + W_21 tanh(x2)\n",
                    "# dx2/dt = 0 => x2 = W_12 tanh(x1) + W_22 tanh(x2)\n",
                    "plt.contour(X1, X2, -X1 + W_rnn[0,0]*np.tanh(X1) + W_rnn[0,1]*np.tanh(X2), [0], colors='magenta', linestyles='--', linewidths=2, label='$dx_1/dt=0$ Nullcline')\n",
                    "plt.contour(X1, X2, -X2 + W_rnn[1,0]*np.tanh(X1) + W_rnn[1,1]*np.tanh(X2), [0], colors='cyan', linestyles='--', linewidths=2, label='$dx_2/dt=0$ Nullcline')\n",
                    "\n",
                    "# Simulate trajectories starting from different initial conditions\n",
                    "init_conditions = [\n",
                    "    np.array([-2.0, -1.0]),\n",
                    "    np.array([2.0, 1.0]),\n",
                    "    np.array([-0.2, 0.4]),\n",
                    "    np.array([0.4, -0.2])\n",
                    "]\n",
                    "\n",
                    "dt_rnn = 0.5\n",
                    "t_rnn_steps = 100\n",
                    "for x_init in init_conditions:\n",
                    "    traj = np.zeros((t_rnn_steps, 2))\n",
                    "    traj[0] = x_init\n",
                    "    for step in range(1, t_rnn_steps):\n",
                    "        deriv = rnn_deriv(traj[step-1])\n",
                    "        traj[step] = traj[step-1] + deriv * dt_rnn\n",
                    "    plt.plot(traj[:, 0], traj[:, 1], color='#f59e0b', lw=3, alpha=0.9)\n",
                    "    plt.plot(traj[0, 0], traj[0, 1], 'o', color='#ef4444', markersize=6)\n",
                    "    plt.plot(traj[-1, 0], traj[-1, 1], 'x', color='#10b981', markersize=8, mew=2)\n",
                    "\n",
                    "plt.axhline(0, color='gray', alpha=0.3, ls=':')\n",
                    "plt.axvline(0, color='gray', alpha=0.3, ls=':')\n",
                    "plt.title('Phase Portrait & Attractors of a 2-Unit RNN', fontsize=14)\n",
                    "plt.xlabel('State of Unit 1 ($x_1$)', fontsize=11)\n",
                    "plt.ylabel('State of Unit 2 ($x_2$)', fontsize=11)\n",
                    "plt.grid(True, alpha=0.15)\n",
                    "plt.show()"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### 3.2 Interpretation of the Phase Portrait\n",
                    "Looking at the plot above:\n",
                    "1. **Attractors (Green X)**: There are two stable fixed points (in the top-right and bottom-left quadrants). Trajectories starting in these basins of attraction converge here. This acts as a **bistable memory motif**.\n",
                    "2. **Saddle Point (Origin 0,0)**: The origin is an unstable fixed point. If a trajectory starts exactly on the diagonal dividing line (separatrix), it will flow towards the origin and then slide off to one of the stable attractors. This is a **decision-making saddle motif**.\n",
                    "3. **Nullclines (Magenta and Cyan)**: The intersections of the nullclines are the exact positions of the fixed points! You can clearly see three intersection points (two stable, one unstable)."
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### 3.3 The FORCE Algorithm (Sussillo & Abbott, 2009)\n",
                    "The FORCE algorithm (First-Order Reduced Controller for RNNs) trains a chaotic, high-dimensional Recurrent Neural Network to generate complex, high-frequency, non-linear trajectories by feeding back the output to the network and modifying the output weights $W^{out}$ online using **Recursive Least Squares (RLS)**.\n",
                    "\n",
                    "Let's write a simplified simulation of the **FORCE Algorithm** stabilizing chaotic neural activity to generate a target sine-wave pattern."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Let's set up a network of N = 100 units\n",
                    "N = 100\n",
                    "g = 1.5           # Chaos scale (g > 1.0 means highly chaotic free-running dynamics)\n",
                    "alpha = 1.0       # RLS initialization scale\n",
                    "dt_f = 0.5\n",
                    "T_f = 600.0\n",
                    "t_f = np.arange(0, T_f, dt_f)\n",
                    "\n",
                    "np.random.seed(42)\n",
                    "\n",
                    "# Sparse random connectivity matrix with normal distribution\n",
                    "W_M = np.random.normal(0.0, g / np.sqrt(N), size=(N, N))\n",
                    "# Output feedback matrix (feedback of generated signal into network)\n",
                    "W_fb = np.random.uniform(-1.0, 1.0, size=(N, 1))\n",
                    "# Readout weights initialized to zero\n",
                    "W_out = np.zeros((N, 1))\n",
                    "\n",
                    "# Recursive Least Squares correlation matrix inverse\n",
                    "P = np.eye(N) * alpha\n",
                    "\n",
                    "# Target function: A complex signal we want to learn (e.g. combination of two frequencies)\n",
                    "target = 1.0 * np.sin(2 * np.pi * 0.01 * t_f) + 0.5 * np.cos(2 * np.pi * 0.025 * t_f)\n",
                    "\n",
                    "# Run variables\n",
                    "x = np.random.normal(0.0, 0.1, size=(N, 1))\n",
                    "r = np.tanh(x)\n",
                    "z = np.dot(W_out.T, r)[0, 0] # Output read-out\n",
                    "\n",
                    "# Output stores\n",
                    "outputs = np.zeros(len(t_f))\n",
                    "network_states = np.zeros((len(t_f), 3)) # Track 3 units\n",
                    "\n",
                    "print(\"Training RNN using FORCE algorithm...\")\n",
                    "for i in range(len(t_f)):\n",
                    "    # ODE Euler Step\n",
                    "    # Internal states update driven by recurrent connections and feedback of current output\n",
                    "    dx_dt = (-x + np.dot(W_M, r) + np.dot(W_fb, z)) / 10.0\n",
                    "    x = x + dx_dt * dt_f\n",
                    "    r = np.tanh(x)\n",
                    "    \n",
                    "    # RLS Update (FORCE training phase - active for the first 80% of simulation)\n",
                    "    if i < int(0.8 * len(t_f)) and i % 2 == 0:\n",
                    "        # Calculate projected matrix multiplication\n",
                    "        k_vec = np.dot(P, r)\n",
                    "        c_val = 1.0 / (1.0 + np.dot(r.T, k_vec)[0, 0])\n",
                    "        P = P - c_val * np.dot(k_vec, k_vec.T)\n",
                    "        \n",
                    "        # Read out error\n",
                    "        z = np.dot(W_out.T, r)[0, 0]\n",
                    "        error = target[i] - z\n",
                    "        \n",
                    "        # Update readout weights\n",
                    "        W_out = W_out + error * c_val * k_vec\n",
                    "        \n",
                    "    # Calculate readout with new weights\n",
                    "    z = np.dot(W_out.T, r)[0, 0]\n",
                    "    outputs[i] = z\n",
                    "    network_states[i, :] = r[:3, 0]\n",
                    "\n",
                    "print(\"FORCE Training completed!\")\n",
                    "\n",
                    "# Plot FORCE results\n",
                    "fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 7), sharex=True, dpi=100)\n",
                    "\n",
                    "# Training vs Test border\n",
                    "border_t = t_f[int(0.8 * len(t_f))]\n",
                    "\n",
                    "ax1.plot(t_f, target, color='#64748b', lw=3, label='Target Signal (Ideal)', alpha=0.5)\n",
                    "ax1.plot(t_f, outputs, color='#8b5cf6', lw=2, label='RNN Generated $z(t)$')\n",
                    "ax1.axvline(border_t, color='#ef4444', ls='--', lw=2)\n",
                    "ax1.text(border_t - 65, 1.2, 'FORCE Learning ACTIVE', color='#ef4444', fontweight='bold')\n",
                    "ax1.text(border_t + 5, 1.2, 'Free Running TEST (Weights FROZEN)', color='#10b981', fontweight='bold')\n",
                    "ax1.set_ylabel('Output Amplitude', fontsize=11)\n",
                    "ax1.set_title('Stabilizing Chaos to Generate Target Pattern (FORCE Algorithm)', fontsize=14)\n",
                    "ax1.legend()\n",
                    "ax1.grid(True, alpha=0.2)\n",
                    "\n",
                    "ax2.plot(t_f, network_states[:, 0], color='#06b6d4', label='Unit 1 Firing Rate $h_1(t)$', alpha=0.8)\n",
                    "ax2.plot(t_f, network_states[:, 1], color='#10b981', label='Unit 2 Firing Rate $h_2(t)$', alpha=0.8)\n",
                    "ax2.plot(t_f, network_states[:, 2], color='#d97706', label='Unit 3 Firing Rate $h_3(t)$', alpha=0.8)\n",
                    "ax2.axvline(border_t, color='#ef4444', ls='--', lw=2)\n",
                    "ax2.set_xlabel('Time (ms)', fontsize=11)\n",
                    "ax2.set_ylabel('Firing Rate $\\\\tanh(x_i)$', fontsize=11)\n",
                    "ax2.legend()\n",
                    "ax2.grid(True, alpha=0.2)\n",
                    "\n",
                    "plt.tight_layout()\n",
                    "plt.show()"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "### 3.4 Summary of David Sussillo's RNN Population Dynamics\n",
                    "From this experiment, we observe a vital lesson about continuous recurrent neural networks:\n",
                    "1. **Stabilizing Chaos**: Free-running random networks with strong connections ($g > 1.0$) are chaotic and behave unpredictably. However, the **FORCE algorithm** can stabilize this chaos dynamically, matching complex target signals by modifying *only* the readout weights and feeding back the error.\n",
                    "2. **State Space Representation**: Rather than a single neuron controlling a single action, the collective state space of $N$ units forms a low-dimensional trajectory (like an orbit or limit cycle) that carries the coding representation. This is the cornerstone of **Computation through Neural Population Dynamics**."
                ]
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }

    workspace_dir = "c:\\Users\\User\\2026Antigravity"
    notebook_path = os.path.join(workspace_dir, "Neurodynamics_Sussillo_FORCE.ipynb")
    
    with open(notebook_path, "w", encoding="utf-8") as f:
        json.dump(notebook, f, indent=2, ensure_ascii=False)
    
    print(f"Jupyter Notebook successfully written to: {notebook_path}")

if __name__ == "__main__":
    create_notebook()
